# Generated by Django 5.2.8 on 2025-12-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techlog_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechlogTools2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True)),
                ('image', models.ImageField(upload_to='techlog_tools/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='techlogtools',
            name='image',
            field=models.ImageField(upload_to='techlog_tools/images/'),
        ),
    ]
