# Generated by Django 5.2.8 on 2025-12-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelogSpparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='techlog_tools/images_spparts/')),
                ('price_order', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('product_code', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
