# Generated by Django 5.2.8 on 2025-12-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telog_spparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telogspparts',
            name='instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
