# Generated by Django 5.2.8 on 2026-02-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telog_spparts', '0003_repairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telogspparts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
